// This file is autogenerated. Do not edit manually.

export interface Order {
  id: number;
  name: string;
  description: string;
  cost: number;
  reason_for_purchase: string;
}

export interface NewOrder {
  name: string;
  description: string;
  cost: number;
  reason_for_purchase: string;
}