import ast
import os
from pathlib import Path

def map_type(py_type):
    mapping = {
        'str': 'string',
        'int': 'number',
        'float': 'number',
        'bool': 'boolean',
        'Any': 'any',
    }
    return mapping.get(py_type, 'any')

def parse_models(file_path):
    with open(file_path, 'r') as f:
        node = ast.parse(f.read())
    
    types = []
    for item in node.body:
        if isinstance(item, ast.ClassDef):
            # Check if it inherits from BaseModel
            is_pydantic = any(
                (isinstance(base, ast.Name) and base.id == 'BaseModel') or
                (isinstance(base, ast.Attribute) and base.attr == 'BaseModel')
                for base in item.bases
            )
            if not is_pydantic:
                continue
            
            fields = []
            for item_body in item.body:
                if isinstance(item_body, ast.AnnAssign) and isinstance(item_body.target, ast.Name):
                    field_name = item_body.target.id
                    # Extract type name
                    if isinstance(item_body.annotation, ast.Name):
                        type_name = item_body.annotation.id
                    else:
                        type_name = 'any'
                    fields.append(f"  {field_name}: {map_type(type_name)};")
            
            if fields:
                type_def = f"export interface {item.name} {{\n" + "\n".join(fields) + "\n}"
                types.append(type_def)
    
    return types

def main():
    backend_models_dir = Path('backend/models')
    frontend_types_file = Path('frontend/types/models.ts')
    
    all_types = []
    for py_file in backend_models_dir.glob('*.py'):
        if py_file.name == '__init__.py':
            continue
        all_types.extend(parse_models(py_file))
    
    if not all_types:
        print("No Pydantic models found.")
        return

    frontend_types_file.parent.mkdir(parents=True, exist_ok=True)
    with open(frontend_types_file, 'w') as f:
        f.write("// This file is autogenerated. Do not edit manually.\n\n")
        f.write("\n\n".join(all_types))
    
    print(f"Successfully generated types in {frontend_types_file}")

if __name__ == "__main__":
    main()